// Thish file is generated by quicktype,
// check /tools/codegen for further information.
// DO NOT EDIT IT.

//  To parse this JSON data, first install
//
//      json.hpp  https://github.com/nlohmann/json
//
//  Then include this file, and then do
//
//     CunningProperties.hpp data = nlohmann::json::parse(jsonString);
//
//  You can get std::wstring data back out using
//
//     std::wcout << wdump((nlohmann::json) Schema);

#pragma once

#include <optional>
#include <nlohmann/json.hpp>
#include "helper.hpp"

#include "FilePath.hpp"

namespace ocppi {
namespace runtime {
namespace config {
using nlohmann::json;

struct CunningProperties {
FilePath linkname;
FilePath lowerLink;
FilePath allowedAddress;
FilePath configureAllowedAddress;
FilePath defrouter;
FilePath macAddress;
FilePath linkProtection;
};
}
}
}

