// Thish file is generated by quicktype,
// check /tools/codegen for further information.
// DO NOT EDIT IT.

//  To parse this JSON data, first install
//
//      json.hpp  https://github.com/nlohmann/json
//
//  Then include this file, and then do
//
//     ProcessProperties.hpp data = nlohmann::json::parse(jsonString);
//
//  You can get std::wstring data back out using
//
//     std::wcout << wdump((nlohmann::json) Schema);

#pragma once

#include <optional>
#include <nlohmann/json.hpp>
#include "helper.hpp"

#include "Env.hpp"
#include "FilePath.hpp"
#include "ConsoleSize.hpp"
#include "User.hpp"
#include "FluffyCapabilities.hpp"
#include "IoPriority.hpp"
#include "Scheduler.hpp"
#include "Rlimits.hpp"

namespace ocppi {
namespace runtime {
namespace config {
using nlohmann::json;

struct ProcessProperties {
Env args;
FilePath commandLine;
ConsoleSize consoleSize;
FilePath cwd;
Env env;
FilePath terminal;
User user;
FluffyCapabilities capabilities;
FilePath apparmorProfile;
FilePath oomScoreAdj;
FilePath selinuxLabel;
IoPriority ioPriority;
FilePath noNewPrivileges;
Scheduler scheduler;
Rlimits rlimits;
};
}
}
}

