// Thish file is generated by quicktype,
// check /tools/codegen for further information.
// DO NOT EDIT IT.

//  To parse this JSON data, first install
//
//      json.hpp  https://github.com/nlohmann/json
//
//  Then include this file, and then do
//
//     Schema.hpp data = nlohmann::json::parse(jsonString);
//
//  You can get std::wstring data back out using
//
//     std::wcout << wdump((nlohmann::json) Schema);

#pragma once

#include <optional>
#include <nlohmann/json.hpp>
#include "helper.hpp"

#include "Linux.hpp"
#include "SchemaProperties.hpp"
#include "Solaris.hpp"
#include "Vm.hpp"
#include "Windows.hpp"
#include "Zos.hpp"
#include "Definitions.hpp"

namespace ocppi {
namespace runtime {
namespace config {
enum class FilePathType : int;
}
}
}

namespace ocppi {
namespace runtime {
namespace config {
using nlohmann::json;

struct Schema {
std::optional<Linux> linux;
std::optional<std::wstring> description;
std::optional<std::wstring> schema;
std::optional<FilePathType> type;
std::optional<SchemaProperties> properties;
std::optional<std::vector<std::wstring>> required;
std::optional<Solaris> solaris;
std::optional<Vm> vm;
std::optional<Windows> windows;
std::optional<Zos> zos;
std::optional<Definitions> definitions;
};
}
}
}

// stdout

//  To parse this JSON data, first install
//
//      json.hpp  https://github.com/nlohmann/json
//
//  Then include this file, and then do
//
//     stdout data = nlohmann::json::parse(jsonString);
//
//  You can get std::wstring data back out using
//
//     std::wcout << wdump((nlohmann::json) Schema);

#pragma once

#include <optional>
#include <nlohmann/json.hpp>
#include "helper.hpp"

#include "Env.hpp"
#include "ArrayOfGIDsType.hpp"
#include "ArrayOfGiDs.hpp"
#include "FilePathType.hpp"
#include "FilePath.hpp"
#include "ArrayOfStrings.hpp"
#include "BlockIODeviceProperties.hpp"
#include "BlockIODevice.hpp"
#include "PurpleProperties.hpp"
#include "BlockIODeviceThrottleAllOf.hpp"
#include "BlockIODeviceThrottle.hpp"
#include "FluffyProperties.hpp"
#include "BlockIODeviceWeightAllOf.hpp"
#include "BlockIODeviceWeight.hpp"
#include "NamespaceType.hpp"
#include "DeviceProperties.hpp"
#include "Device.hpp"
#include "DeviceCgroupProperties.hpp"
#include "DeviceCgroup.hpp"
#include "FileMode.hpp"
#include "FileType.hpp"
#include "Pid.hpp"
#include "HookProperties.hpp"
#include "Hook.hpp"
#include "IdMappingProperties.hpp"
#include "IdMapping.hpp"
#include "Major.hpp"
#include "PatternProperties.hpp"
#include "MapStringString.hpp"
#include "MountProperties.hpp"
#include "Mount.hpp"
#include "NamespaceReferenceProperties.hpp"
#include "NamespaceReference.hpp"
#include "NetworkInterfacePriorityProperties.hpp"
#include "NetworkInterfacePriority.hpp"
#include "OciVersion.hpp"
#include "PersonalityProperties.hpp"
#include "Personality.hpp"
#include "RdmaProperties.hpp"
#include "Rdma.hpp"
#include "Names.hpp"
#include "SyscallProperties.hpp"
#include "Syscall.hpp"
#include "SyscallArgProperties.hpp"
#include "SyscallArg.hpp"
#include "TimeOffsetsProperties.hpp"
#include "TimeOffsets.hpp"
#include "Definitions.hpp"
#include "ApparmorProperties.hpp"
#include "Apparmor.hpp"
#include "MemBWSchemaClass.hpp"
#include "PurpleCapabilities.hpp"
#include "CgroupProperties.hpp"
#include "Cgroup.hpp"
#include "IntelRdtProperties.hpp"
#include "IntelRdt.hpp"
#include "NamespacesItems.hpp"
#include "Namespaces.hpp"
#include "PersonalityClass.hpp"
#include "BlockIOProperties.hpp"
#include "BlockIO.hpp"
#include "StickyProperties.hpp"
#include "PurpleCPU.hpp"
#include "IndigoProperties.hpp"
#include "HugepageLimitsItems.hpp"
#include "HugepageLimits.hpp"
#include "IndecentProperties.hpp"
#include "PurpleMemory.hpp"
#include "HilariousProperties.hpp"
#include "PurpleNetwork.hpp"
#include "PidsProperties.hpp"
#include "Pids.hpp"
#include "RdmaClass.hpp"
#include "TentacledProperties.hpp"
#include "PurpleResources.hpp"
#include "SeccompProperties.hpp"
#include "Seccomp.hpp"
#include "TimeOffsetsPropertiesClass.hpp"
#include "TimeOffsetsClass.hpp"
#include "LinuxProperties.hpp"
#include "Linux.hpp"
#include "HooksProperties.hpp"
#include "Hooks.hpp"
#include "CapabilitiesProperties.hpp"
#include "FluffyCapabilities.hpp"
#include "ConsoleSizeProperties.hpp"
#include "ConsoleSize.hpp"
#include "IoPriorityProperties.hpp"
#include "IoPriority.hpp"
#include "AmbitiousProperties.hpp"
#include "RlimitsItems.hpp"
#include "Rlimits.hpp"
#include "SchedulerProperties.hpp"
#include "Scheduler.hpp"
#include "UserProperties.hpp"
#include "User.hpp"
#include "ProcessProperties.hpp"
#include "Process.hpp"
#include "RootProperties.hpp"
#include "Root.hpp"
#include "SchemaProperties.hpp"
#include "CunningProperties.hpp"
#include "AnetItems.hpp"
#include "Anet.hpp"
#include "CappedCPUProperties.hpp"
#include "CappedCPU.hpp"
#include "CappedMemoryProperties.hpp"
#include "CappedMemory.hpp"
#include "SolarisProperties.hpp"
#include "Solaris.hpp"
#include "HypervisorProperties.hpp"
#include "Hypervisor.hpp"
#include "ImageProperties.hpp"
#include "Image.hpp"
#include "KernelProperties.hpp"
#include "Kernel.hpp"
#include "VmProperties.hpp"
#include "Vm.hpp"
#include "HypervProperties.hpp"
#include "Hyperv.hpp"
#include "LayerFolders.hpp"
#include "MagentaProperties.hpp"
#include "FluffyNetwork.hpp"
#include "MischievousProperties.hpp"
#include "FluffyCPU.hpp"
#include "FluffyMemory.hpp"
#include "StorageProperties.hpp"
#include "Storage.hpp"
#include "FriskyProperties.hpp"
#include "FluffyResources.hpp"
#include "WindowsProperties.hpp"
#include "Windows.hpp"
#include "ZosProperties.hpp"
#include "Zos.hpp"
#include "Schema.hpp"
namespace ocppi {
namespace runtime {
namespace config {
}
}
}
