// Thish file is generated by quicktype,
// check /tools/codegen for further information.
// DO NOT EDIT IT.

//  To parse this JSON data, first install
//
//      json.hpp  https://github.com/nlohmann/json
//
//  Then include this file, and then do
//
//     SeccompProperties.hpp data = nlohmann::json::parse(jsonString);
//
//  You can get std::wstring data back out using
//
//     std::wcout << wdump((nlohmann::json) Schema);

#pragma once

#include <optional>
#include <nlohmann/json.hpp>
#include "helper.hpp"

#include "Env.hpp"
#include "ArrayOfGiDs.hpp"
#include "FilePath.hpp"

namespace ocppi {
namespace runtime {
namespace config {
using nlohmann::json;

struct SeccompProperties {
std::optional<Env> defaultAction;
std::optional<Env> defaultErrnoRet;
std::optional<ArrayOfGiDs> flags;
std::optional<FilePath> listenerPath;
std::optional<FilePath> listenerMetadata;
std::optional<ArrayOfGiDs> architectures;
std::optional<ArrayOfGiDs> syscalls;
std::optional<FilePath> enabled;
std::optional<ArrayOfGiDs> actions;
std::optional<ArrayOfGiDs> operators;
std::optional<ArrayOfGiDs> archs;
std::optional<ArrayOfGiDs> knownFlags;
std::optional<ArrayOfGiDs> supportedFlags;
};
}
}
}

