// Thish file is generated by quicktype,
// check /tools/codegen for further information.
// DO NOT EDIT IT.

//  To parse this JSON data, first install
//
//      json.hpp  https://github.com/nlohmann/json
//
//  Then include this file, and then do
//
//     WindowsProperties.hpp data = nlohmann::json::parse(jsonString);
//
//  You can get std::wstring data back out using
//
//     std::wcout << wdump((nlohmann::json) Schema);

#pragma once

#include <optional>

#include <nlohmann/json.hpp>

#include "ArrayOfGiDs.hpp"
#include "FilePath.hpp"
#include "FluffyNetwork.hpp"
#include "FluffyResources.hpp"
#include "Hyperv.hpp"
#include "LayerFolders.hpp"
#include "helper.hpp"

namespace ocppi
{
namespace runtime
{
namespace config
{
using nlohmann::json;

struct WindowsProperties {
        LayerFolders layerFolders;
        ArrayOfGiDs devices;
        FluffyResources resources;
        FluffyNetwork network;
        FilePath credentialSpec;
        FilePath servicing;
        FilePath ignoreFlushesDuringBoot;
        Hyperv hyperv;
};
}
}
}
